// Birds edge Worker — entrypoint.
// Routes: /ingest (sensor), /ws (live), /media/* (R2), /api/* (read), SPA assets.
import { Hono } from "hono";
import type { ArtJob, Bindings } from "./types";
import { handleIngest } from "./ingest";
import { backfillSpeciesPhotos, handleArtBatch } from "./art";
import { api } from "./api";
import { contentTypeFor } from "./media";
import { regenerateFrame, renderFrameHtml } from "./frame";
import { ingestMacaulay, type MacaulayIngest } from "./macaulay";

export { Aviary } from "./aviary";

const app = new Hono<{ Bindings: Bindings }>();

// Content-Security-Policy for HTML responses. img-src must stay in sync with
// the external photo-host allowlist in media.ts (safeExternalUrl); the static
// copy of these headers for directly-served assets lives in web/public/_headers.
// style-src needs 'unsafe-inline': the SPA and /frame set style attributes.
// connect-src 'self' covers same-origin fetch + the /ws WebSocket.
const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: https://cdn.download.ams.birds.cornell.edu https://www.allaboutbirds.org https://celebrateurbanbirds.org https://www.celebrateurbanbirds.org https://static.inaturalist.org https://inaturalist-open-data.s3.amazonaws.com",
  "media-src 'self'",
  "connect-src 'self'",
  "font-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
].join("; ");

// Security headers on every response this Worker builds (API JSON, /media,
// SPA fallback, /frame). Assets served directly by Workers Assets get the same
// set from web/public/_headers, so only set what isn't already present.
app.use("*", async (c, next) => {
  await next();
  if (c.res.status === 101) return; // WebSocket upgrade: headers are immutable
  const res = new Response(c.res.body, c.res);
  const h = res.headers;
  if (!h.has("X-Content-Type-Options")) h.set("X-Content-Type-Options", "nosniff");
  if (!h.has("Referrer-Policy")) h.set("Referrer-Policy", "strict-origin-when-cross-origin");
  if ((h.get("Content-Type") ?? "").includes("text/html")) {
    if (!h.has("Content-Security-Policy")) h.set("Content-Security-Policy", CSP);
    if (!h.has("X-Frame-Options")) h.set("X-Frame-Options", "DENY");
    if (!h.has("Permissions-Policy"))
      h.set("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
  }
  c.res = res;
});

app.get("/healthz", (c) => c.json({ ok: true, service: "birds-edge" }));

// Sensor ingest (authenticated).
app.post("/ingest", handleIngest);

// WebSocket live feed -> proxied to the single global Aviary DO.
app.get("/ws", (c) => {
  if (c.req.header("Upgrade") !== "websocket") {
    return c.text("expected websocket", 426);
  }
  const aviary = c.env.AVIARY.get(c.env.AVIARY.idFromName("global"));
  return aviary.fetch(c.req.raw);
});

// Frame render target for the e-paper panel (screenshotted by the cron job).
app.get("/frame", async (c) => {
  return c.html(await renderFrameHtml(c.env));
});

// Serve media from R2 with long-lived caching (immutable, content-addressed).
app.get("/media/*", async (c) => {
  const key = c.req.path.slice("/media/".length);
  if (!key) return c.notFound();

  // Gate the e-paper frame image behind a shared key so crawlers don't fetch
  // it (mirrors Avian's approach). Only enforced when FRAME_KEY is configured.
  if (key.startsWith("frame/") && c.env.FRAME_KEY) {
    if (c.req.query("k") !== c.env.FRAME_KEY) return c.json({ error: "forbidden" }, 403);
  }

  // The frame image is mutable (regenerated by cron); everything else is
  // content-addressed and immutable.
  const isFrame = key.startsWith("frame/");

  const cache = caches.default;
  if (!isFrame) {
    const cached = await cache.match(c.req.raw);
    if (cached) return cached;
  }

  const obj = await c.env.MEDIA.get(key);
  if (!obj) return c.notFound();

  const headers = new Headers();
  obj.writeHttpMetadata(headers);
  headers.set("Content-Type", obj.httpMetadata?.contentType ?? contentTypeFor(key));
  headers.set("Cache-Control", isFrame ? "public, max-age=60" : "public, max-age=31536000, immutable");
  headers.set("ETag", obj.httpEtag);

  const res = new Response(obj.body, { headers });
  if (!isFrame) c.executionCtx.waitUntil(cache.put(c.req.raw, res.clone()));
  return res;
});

// Authenticated admin: wipe all detections/species/art + the live buffer.
app.post("/admin/reset", async (c) => {
  const auth = c.req.header("Authorization") ?? "";
  if (!c.env.INGEST_TOKEN || auth !== `Bearer ${c.env.INGEST_TOKEN}`) {
    return c.json({ error: "unauthorized" }, 401);
  }
  await c.env.DB.batch([
    c.env.DB.prepare("DELETE FROM detections"),
    c.env.DB.prepare("DELETE FROM art_assets"),
    c.env.DB.prepare("DELETE FROM species"),
  ]);
  const aviary = c.env.AVIARY.get(c.env.AVIARY.idFromName("global"));
  await aviary.reset();
  return c.json({ ok: true, cleared: true });
});

// Authenticated admin: regenerate the e-paper frame image on demand.
app.post("/admin/frame", async (c) => {
  const auth = c.req.header("Authorization") ?? "";
  if (!c.env.INGEST_TOKEN || auth !== `Bearer ${c.env.INGEST_TOKEN}`) {
    return c.json({ error: "unauthorized" }, 401);
  }
  const bytes = await regenerateFrame(c.env);
  return c.json({ ok: true, bytes });
});

// Authenticated admin: ingest scraped eBird/Macaulay photos for a species.
// The Playwright stealth scraper (tools/macaulay_scraper) posts an eBird code +
// asset ids here; we cache them in KV (modal carousel) and mirror the top photo
// into R2 as the collage tile. Only asset ids/credits are trusted — the image
// URL is rebuilt server-side from the asset id.
app.post("/admin/macaulay", async (c) => {
  const auth = c.req.header("Authorization") ?? "";
  if (!c.env.INGEST_TOKEN || auth !== `Bearer ${c.env.INGEST_TOKEN}`) {
    return c.json({ error: "unauthorized" }, 401);
  }
  let body: MacaulayIngest;
  try {
    body = (await c.req.json()) as MacaulayIngest;
  } catch {
    return c.json({ error: "invalid json" }, 400);
  }
  try {
    const result = await ingestMacaulay(c.env, body);
    return c.json({ ok: true, ...result });
  } catch (e) {
    return c.json({ error: String((e as Error).message) }, 400);
  }
});

// Authenticated admin: backfill collage photos for species missing one
// (photo_key IS NULL). eBird photos arrive via the scraper (POST /admin/macaulay);
// this re-runs the photo resolver (eBird-if-scraped, else Wikipedia) so a missed
// first-sighting photo self-heals instead of showing the AI illustration.
// Optional ?limit=N (default 50).
app.post("/admin/backfill-photos", async (c) => {
  const auth = c.req.header("Authorization") ?? "";
  if (!c.env.INGEST_TOKEN || auth !== `Bearer ${c.env.INGEST_TOKEN}`) {
    return c.json({ error: "unauthorized" }, 401);
  }
  const limit = Math.min(Math.max(Number(c.req.query("limit") ?? "50"), 1), 200);
  const result = await backfillSpeciesPhotos(c.env, limit);
  return c.json({ ok: true, ...result });
});

// Read API.
app.route("/api", api);

// Everything else -> built dashboard SPA (Workers Assets). Falls back to a
// placeholder until the web/ app is built in Phase 2.
app.get("*", async (c) => {
  // Unknown API routes must 404 as JSON, not fall through to the SPA shell.
  if (c.req.path.startsWith("/api/")) return c.json({ error: "not found" }, 404);
  if (c.env.ASSETS) {
    const res = await c.env.ASSETS.fetch(c.req.raw);
    if (res.status !== 404) return res;
  }
  return c.html(
    "<!doctype html><meta charset=utf-8><title>birds.aperauch.com</title>" +
      "<body style='font-family:system-ui;background:#f5efe0;color:#3a3226;padding:3rem'>" +
      "<h1>🐦 birds.aperauch.com</h1><p>Edge backbone is live. Dashboard lands in Phase 2.</p>" +
      "<p><a href='/api/recent'>/api/recent</a> · <a href='/api/stats'>/api/stats</a> · " +
      "<a href='/healthz'>/healthz</a></p></body>",
  );
});

export default {
  fetch: app.fetch,
  async queue(batch: MessageBatch<ArtJob>, env: Bindings): Promise<void> {
    await handleArtBatch(batch, env);
  },
  // Cron Trigger: regenerate the e-paper frame image (see wrangler.jsonc crons).
  async scheduled(_event: ScheduledController, env: Bindings, ctx: ExecutionContext): Promise<void> {
    ctx.waitUntil(
      regenerateFrame(env)
        .then(() => undefined)
        .catch((e) => console.error("frame regenerate failed", e)),
    );
    // Self-heal: backfill a few species still missing a collage photo so a missed
    // first-sighting photo recovers automatically instead of showing AI art.
    ctx.waitUntil(
      backfillSpeciesPhotos(env, 3)
        .then((r) => {
          if (r.fixed) console.log(`photo backfill: fixed ${r.fixed}/${r.scanned}`);
        })
        .catch((e) => console.error("photo backfill failed", e)),
    );
  },
} satisfies ExportedHandler<Bindings, ArtJob>;
